export const textStatic = {
    txt1: "Hello, I am",
    txt2: "Siwat Photinam",
    txt3: "I am",
    txt4: "Actively",
    txt5: "seeking",
    txt6: "an opportunity",
    txt7: "to join Data Analyst or Web Developer Team.",
    txt8: "Have",
    txt9: "expertise in Systems Analyst, ",
    txt10: "especially in",
    txt11: "SAP,",
    txt12: "with", 
    txt13: "Data Analysis skill.",
    txt14: "Enthusiastic",
    txt15: "about",
    txt16: "learning",
    txt17: "what it takes",
    txt18: "to become a Data Analyst or Web Developer.",
    txt19: "Resume",
    txt20: "E-mail",
};
