import colmar from "../assets/colmar.png";
import fitbod from "../assets/fitbod.png";
import findhat from "../assets/findyourhat.png";
import travelpic from "../assets/travel-data.png";
import travelDoc from "../assets/data-travel-project.pdf";

export const ProjectList = [
   {img: fitbod,
       name: "Build the Fitness Website (Group Project)",
       des1: "• Implemented the website, following the final project sprint assigned by Generation.",
       des2: "• Ultilized MERN Full Stack Skills to develop the website.",
       link1: "https://fitbod-fityourgoal.vercel.app/",
       link2: "https://github.com/JSD5-5-Group-10/Front-End",
       color: "blue",
       req1: "Launch",
       req2: "Code",
    },
    {img: travelpic,
      name: "Airline Passenger Satisfaction Analysis",
      des1: "• Identified significant factors affecting passenger satisfaction from services or products.",
      des2: "• Utilized Python libraries to analyze and visualize data.",
      link1: travelDoc,
      link2: "https://colab.research.google.com/drive/1ALPc6FrxzOwQRhCM2aWc_yt0BRQVQhDt#scrollTo=Nj5OsgFVzGF9",
      color: "yellow",
      req1: "Launch",
      req2: "Code",
    },
    {img: findhat,
       name: "Build the Find Your Hat Game",
       des1: "• Implemented the game, following the requirements provided by codecademy.com.",
       des2: "• Applied JavaScript Fundamentals to construct this game.",
       link1: "https://replit.com/@SIWATPHOTINAM/42-find-your-hat#index.js",
       link2: "https://replit.com/@SIWATPHOTINAM/42-find-your-hat#index.js",
       color: "blue",
       req1: "Launch",
       req2: "Code",
    },
    {img: colmar,
      name: "Build the Colmar Academy Webpage",
      des1: "• Implemented the webpage, following the wireframes provided by codecademy.com.",
      des2: "• Made all the necessary design decisions to complete the page.",
      link1: "https://colmar-assessment.vercel.app/",
      link2: "https://github.com/siwatoa/colmar_assessment",
      color: "blue",
      req1: "Launch",
      req2: "Code",
    },
];
